apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: infotoast
  namespace: tsm

spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 580Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: macgyver
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: syfohelsenettproxy
          namespace: teamsykmelding
        - application: tsm-pdl-cache
          namespace: tsm
  ingresses:
    - "https://infotoast.intern.dev.nav.no"
  env:
    - name: SYFOHELSENETTPROXY_SCOPE
      value: api://dev-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: TSMPDL_SCOPE
      value: api://dev-gcp.tsm.tsm-pdl-cache/.default
    - name: LEGE_SUSPENSJON_PROXY_SCOPE
      value: api://dev-gcp.team-rocket.btsys-api/.default
    - name: TSM_PDL_ENDPOINT_URL
      value: http://tsm-pdl-cache
    - name: SYFOHELSENETTPROXY_URL
      value: http://syfohelsenettproxy.teamsykmelding
    - name: SMTSS_URL
      value: http://smtss
    - name: SMTSS_CLIENT_ID
      value: dev-gcp.teamsykmelding.smtss
    - name: PDL_GRAPHQL_PATH
      value: http://tsm-pdl-cache/graphql
